### ISSUE TITLE
@ryan's garden is not being updated

### ISSUE THREAD

**Issue by ngm** [flancian/agora#11]
Ryan has recently switched to using ox-agora as an intermediary to export org to Agora-compatible .md, and his garden now contains .md files with sensible filenames.

![image](https://user-images.githubusercontent.com/172324/152673157-d90281e0-8cb8-488d-b736-8693780d3fde.png)

However Agora doesn't seem to be picking up these updates, and still only contains the old .org files.  Any ideas why?

![image](https://user-images.githubusercontent.com/172324/152673190-b54265f0-d548-4606-ae1a-f476660b0425.png)

**Comment by flancian** [comment]
Thank you so much for the report! Looking into this.

**Comment by flancian** [comment]
Interestingly whatever happened only affected prod, not dev.anagora.org (which updated fine to this new repo setup).

In prod:

```
agora@thecla:~/agora/garden/ryan$ git pull
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

I checked and dev is pointing to 'main', but prod is pointing to 'master' and was last updated in July 2021 (!). I need to work on 'last updated' monitoring, apologies to Ryan for the oversight.

I'll reset the repo and try to make the importer resilient to this kind of issue.

**Comment by flancian** [comment]
`git checkout main` worked just fine as expected :)

![image](https://user-images.githubusercontent.com/58136431/152680961-d20da2d6-2305-497f-a12c-265c8bf692e0.png)

Thank you for the report!
